"""
Generate Excel template matching Vulnerability_Report_Template_RootNik.docx
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

def create_rootnik_excel_template():
    """Create Excel template with sample data matching RootNik template"""
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Vulnerabilities"
    
    # Define headers matching the template fields
    headers = [
        "Vulnerability ID",      # {{VULN_ID}}
        "Title",                 # {{TITLE}}
        "Risk Level",            # {{RISK_LEVEL}}
        "CVSS Score",            # {{CVSS_SCORE}}
        "CWE ID",                # {{CWE_ID}}
        "Description",           # {{DESCRIPTION}}
        "Affected Components",   # {{AFFECTED_COMPONENTS}}
        "Impact",                # {{IMPACT}}
        "Recommendation",        # {{RECOMMENDATION}}
        "References",            # {{REFERENCES}}
        "Remediation Effort",    # {{REMEDIATION_EFFORT}}
        "POC_Folder",            # Folder name for PoC images
        "Step1",                 # First PoC step
        "Step2",                 # Second PoC step
        "Step3",                 # Third PoC step
        "Step4",                 # Fourth PoC step
        "Step5",                 # Fifth PoC step
    ]
    
    # Style for headers
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="00B0F0", end_color="00B0F0", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Write headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = border
    
    # Sample data - High Risk Vulnerability
    high_vuln_1 = [
        "H1",  # Vulnerability ID
        "Broken Access Control on Jira User Mapping",  # Title
        "High",  # Risk Level
        "7.1 (CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:H/A:N)",  # CVSS Score
        "CWE-284",  # CWE ID
        "During the assessment, RootNik Labs identified that the application is vulnerable to Broken Access Control on Jira User Mapping. This vulnerability allows a low-privileged user (without administrative access) to successfully perform user mapping operations in Jira, which should be restricted to administrators. The flaw lies in the server-side authorization checks, which fail to properly validate the user's privileges when processing requests for user mapping. An attacker can reproduce this by intercepting an administrator's user mapping request, logging in as a non-admin user, and then replacing the intercepted request's authentication tokens (cookies and authorization headers) with those of the low-privileged user before resending the request. This bypasses the UI-level restrictions and grants unauthorized access to a critical administrative function.",  # Description
        "https://example.com/vuln",  # Affected Components
        "An Attacker can perform the following:\n• Unauthorized access to administrative functions\n• Manipulation of user mappings\n• Privilege escalation\n• Potential data breach through unauthorized user management",  # Impact
        "We recommend implementing robust server-side authorization checks for all sensitive operations. Specifically:\n1. Validate user privileges at the API level, not just the UI level\n2. Implement role-based access control (RBAC) consistently across all endpoints\n3. Add audit logging for all administrative actions\n4. Implement request validation to ensure tokens match the required privilege level\n5. Consider implementing additional authentication factors for administrative functions",  # Recommendation
        "https://owasp.org/Top10/A01_2021_Broken_Access_Control/\nhttps://cwe.mitre.org/data/definitions/284.html\nhttps://portswigger.net/web-security/access-control",  # References
        "MEDIUM",  # Remediation Effort
        "H1",  # POC_Folder (folder name where images are stored)
        "Initiate Administrative Action (as User A): As User A (Administrator), navigate to the Jira project's user mapping interface within the designated test organization and initiate a legitimate request to add a user to a Jira project.",  # Step1
        "Intercept the Request: Using an intercepting proxy such as Burp Suite, capture the HTTP request generated by the administrative action in step 1.",  # Step2
        "Switch User Context: Log in to the application as User B, a low-privileged user who does not have administrative access to the test organization or its Jira mappings.",  # Step3
        "Replay with Modified Tokens: Replace the authentication tokens (cookies and authorization headers) in the intercepted request from step 2 with those of User B (obtained after logging in as User B).",  # Step4
        "Complete Unauthorized Action: Send the modified request to the server. Observe that the server accepts the request and successfully performs the user mapping action, despite User B lacking the necessary administrative privileges.",  # Step5
    ]
    
    # Sample data - High Risk Vulnerability 2
    high_vuln_2 = [
        "H2",
        "CSV Injection on Check-in Report",
        "High",
        "7.8 (CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H)",
        "CWE-1236",
        "The application is vulnerable to CSV Injection in the check-in report export functionality. When users export check-in data to CSV format, the application does not properly sanitize user-controlled input fields. An attacker can inject malicious formulas (e.g., =cmd|'/c calc') into check-in fields, which will be executed when the victim opens the exported CSV file in Microsoft Excel or other spreadsheet applications. This can lead to remote code execution on the victim's machine.",
        "https://example.com/check-in/export",
        "An attacker can achieve:\n• Remote Code Execution on victim's machine\n• Data exfiltration from victim's computer\n• Credential theft\n• Malware installation\n• Lateral movement within the organization",
        "1. Sanitize all user input before exporting to CSV format\n2. Prepend potentially dangerous characters (=, +, -, @) with a single quote (')\n3. Implement Content Security Policy for exported files\n4. Add warning messages when opening CSV files with formulas\n5. Use safe CSV export libraries that handle sanitization automatically\n6. Educate users about the risks of opening CSV files from untrusted sources",
        "https://owasp.org/www-community/attacks/CSV_Injection\nhttps://cwe.mitre.org/data/definitions/1236.html\nhttps://www.we45.com/blog/csv-injection-the-insidious-security-flaw",
        "LOW",
        "H2",
        "Create a malicious check-in entry with formula injection: Navigate to the check-in creation page and enter the following payload in the 'Notes' field: =cmd|'/c calc'||'A'!A1",
        "Submit the check-in: Save the malicious check-in entry to the database.",
        "Export check-in report: As an administrator or authorized user, navigate to the check-in report page and click 'Export to CSV'.",
        "Open the exported CSV file: Download the CSV file and open it in Microsoft Excel with macros enabled.",
        "Observe code execution: Notice that the calculator application launches automatically, demonstrating arbitrary code execution on the victim's machine.",
    ]
    
    # Sample data - Low Risk Vulnerability
    low_vuln_1 = [
        "L1",
        "Information Disclosure via Verbose Error Messages",
        "Low",
        "3.7 (CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N)",
        "CWE-209",
        "The application reveals sensitive information through verbose error messages. When certain operations fail, the application returns detailed stack traces and internal system information to the end user. This information includes file paths, database table names, framework versions, and internal architecture details. While this does not directly lead to exploitation, it aids attackers in reconnaissance and can reveal potential attack vectors.",
        "https://example.com/api/*",
        "Information disclosed may help attackers:\n• Understand internal application architecture\n• Identify framework versions with known vulnerabilities\n• Map out file system structure\n• Discover database schema information\n• Plan more targeted attacks based on disclosed information",
        "1. Implement custom error pages that display generic error messages to users\n2. Log detailed error information server-side only\n3. Disable debug mode in production environments\n4. Configure web server to use custom error pages (400, 404, 500, etc.)\n5. Implement centralized error handling that sanitizes error messages\n6. Review all error handling code to ensure sensitive information is not exposed\n7. Set appropriate application environment variables (production vs development)",
        "https://owasp.org/www-community/Improper_Error_Handling\nhttps://cwe.mitre.org/data/definitions/209.html\nhttps://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html",
        "LOW",
        "L1",
        "Trigger an application error: Navigate to an API endpoint and provide invalid input parameters designed to cause an exception (e.g., /api/users/invalid_id).",
        "Observe error response: Review the HTTP response body and notice that it contains a full stack trace with internal file paths and framework information.",
        "Analyze disclosed information: Examine the error message to identify framework versions, internal directory structure, and database table names.",
        "",  # Empty step 4
        "",  # Empty step 5
    ]
    
    # Write sample data
    sample_data = [high_vuln_1, high_vuln_2, low_vuln_1]
    
    for row_idx, vuln_data in enumerate(sample_data, start=2):
        for col_idx, value in enumerate(vuln_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx)
            cell.value = value
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = border
            
            # Color code risk levels
            if col_idx == 3:  # Risk Level column
                if value == "High":
                    cell.fill = PatternFill(start_color="FFE6E6", end_color="FFE6E6", fill_type="solid")
                    cell.font = Font(bold=True, color="CC0000")
                elif value == "Medium":
                    cell.fill = PatternFill(start_color="FFF4E6", end_color="FFF4E6", fill_type="solid")
                    cell.font = Font(bold=True, color="FF8C00")
                elif value == "Low":
                    cell.fill = PatternFill(start_color="E6F3FF", end_color="E6F3FF", fill_type="solid")
                    cell.font = Font(bold=True, color="0066CC")
    
    # Adjust column widths
    column_widths = {
        'A': 15,  # Vulnerability ID
        'B': 40,  # Title
        'C': 12,  # Risk Level
        'D': 50,  # CVSS Score
        'E': 15,  # CWE ID
        'F': 60,  # Description
        'G': 35,  # Affected Components
        'H': 50,  # Impact
        'I': 60,  # Recommendation
        'J': 50,  # References
        'K': 18,  # Remediation Effort
        'L': 15,  # POC_Folder
        'M': 60,  # Step1
        'N': 60,  # Step2
        'O': 60,  # Step3
        'P': 60,  # Step4
        'Q': 60,  # Step5
    }
    
    for col, width in column_widths.items():
        ws.column_dimensions[col].width = width
    
    # Freeze header row
    ws.freeze_panes = "A2"
    
    # Save workbook
    output_file = "/app/RootNik_Vulnerabilities_Template.xlsx"
    wb.save(output_file)
    
    print("✅ Excel template created successfully!")
    print(f"   File: RootNik_Vulnerabilities_Template.xlsx")
    print()
    print("📊 Template includes:")
    print("   - 17 columns matching RootNik template fields")
    print("   - 3 sample vulnerabilities (2 High, 1 Low)")
    print("   - Color-coded risk levels")
    print("   - Formatted headers with blue background")
    print("   - Proper column widths for readability")
    print()
    print("📋 Columns:")
    print("   1. Vulnerability ID")
    print("   2. Title")
    print("   3. Risk Level")
    print("   4. CVSS Score")
    print("   5. CWE ID")
    print("   6. Description")
    print("   7. Affected Components")
    print("   8. Impact")
    print("   9. Recommendation")
    print("   10. References")
    print("   11. Remediation Effort")
    print("   12. POC_Folder")
    print("   13. Step1")
    print("   14. Step2")
    print("   15. Step3")
    print("   16. Step4")
    print("   17. Step5")
    print()
    print("🎯 Sample Data:")
    print("   - H1: Broken Access Control on Jira User Mapping")
    print("   - H2: CSV Injection on Check-in Report")
    print("   - L1: Information Disclosure via Verbose Error Messages")
    print()
    print("💡 Usage:")
    print("   1. Open the Excel file")
    print("   2. Replace sample data with your vulnerabilities")
    print("   3. Use with Phase 2 API to generate Word report")
    print("   4. Template placeholders will be automatically replaced")

if __name__ == '__main__':
    create_rootnik_excel_template()
